# Generated by Django 5.1.4 on 2026-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Video tomosha qilingan foiz (0–100).', verbose_name='tomosha foizi'),
        ),
    ]
