# Generated by Django 5.1.4 on 2026-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='qisqa bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0, verbose_name='bosh sahifa tartibi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='O‘qituvchini landing sahifada chiqarish', verbose_name='bosh sahifada ko‘rsatish'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, help_text='O‘qituvchilar uchun: masalan Algebra, Geometriya', max_length=120, verbose_name='mutaxassislik'),
        ),
    ]
