# Generated by Django 5.1.4 on 2026-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio_customuser_homepage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='yutuqlar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name="ta'lim"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_bio',
            field=models.TextField(blank=True, help_text='Batafsil sahifada chiqadi (asosiy o‘qituvchilar uchun)', verbose_name="to‘liq ma'lumot"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=120, verbose_name='Telegram'),
        ),
    ]
