# Generated by Django 5.1.4 on 2026-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_full_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'O‘quvchi'), ('ADMIN', 'Administrator'), ('TEACHER', 'O‘qituvchi'), ('MODERATOR', 'Moderator')], default='STUDENT', max_length=20, verbose_name='rol'),
        ),
    ]
