# Generated by Django 5.1.4 on 2026-07-29 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
        ('education', '0004_platform_major_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='yulduz')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='izoh')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_ratings', to='education.lesson', verbose_name='dars')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_teacher_ratings', to=settings.AUTH_USER_MODEL, verbose_name='o‘quvchi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_teacher_ratings', to=settings.AUTH_USER_MODEL, verbose_name='o‘qituvchi')),
            ],
            options={
                'verbose_name': 'O‘qituvchi bahosi',
                'verbose_name_plural': 'O‘qituvchi baholari',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher', 'lesson'), name='uniq_student_teacher_lesson_rating')],
            },
        ),
    ]
