# Generated by Django 5.1.4 on 2026-07-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_platform_major_update'),
        ('education', '0004_platform_major_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrating',
            name='stars',
            field=models.PositiveSmallIntegerField(help_text='1 dan 5 gacha', verbose_name='yulduz'),
        ),
        migrations.AddConstraint(
            model_name='teacherrating',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='teacher_rating_stars_1_5'),
        ),
    ]
