# Generated by Django 5.1.4 on 2026-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacher_rating_stars_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bu login allaqachon band.'}, help_text='Istalgan nom — 150 belgigacha.', max_length=150, unique=True, verbose_name='login'),
        ),
    ]
