# Generated by Django 5.1.4 on 2026-07-25 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('full_name', models.CharField(max_length=120, verbose_name='to‘liq ism')),
                ('role_title', models.CharField(help_text='Masalan: Asoschi, CEO, Hammuassis', max_length=120, verbose_name='lavozim')),
                ('bio', models.TextField(blank=True, verbose_name='qisqa bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founders/', verbose_name='rasm')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Asoschi',
                'verbose_name_plural': 'Asoschilar',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('year', models.PositiveIntegerField(verbose_name='yil')),
                ('month', models.PositiveIntegerField(verbose_name='oy')),
                ('highlight', models.CharField(blank=True, help_text='Masalan: Eng faol va yuqori natijali o‘quvchi', max_length=255, verbose_name='izoh')),
                ('is_published', models.BooleanField(default=True, verbose_name='nashr qilingan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_awards', to=settings.AUTH_USER_MODEL, verbose_name='o‘quvchi')),
            ],
            options={
                'verbose_name': 'Oy o‘quvchisi',
                'verbose_name_plural': 'Oy o‘quvchilari',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
