# Generated by Django 5.1.4 on 2026-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='yutuqlar'),
        ),
        migrations.AddField(
            model_name='founder',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name="ta'lim"),
        ),
        migrations.AddField(
            model_name='founder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='founder',
            name='full_bio',
            field=models.TextField(blank=True, help_text='Batafsil sahifada chiqadi', verbose_name="to‘liq ma'lumot"),
        ),
    ]
