# Generated by Django 5.1.4 on 2026-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_full_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('hero_video', models.FileField(blank=True, help_text='Ovozsiz, avtomatik aylanish. Controls yo‘q.', null=True, upload_to='hero/', verbose_name='bosh sahifa video')),
                ('hero_video_active', models.BooleanField(default=True, verbose_name='hero video faol')),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
