# Generated by Django 5.1.4 on 2026-07-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platform_major_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ixtiyoriy: brauzer tab ikonkasi (32×32 yoki 64×64).', null=True, upload_to='branding/', verbose_name='favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG/SVG/JPG — navbar va admin paneldа ko‘rinadi.', null=True, upload_to='branding/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='XYZ', max_length=80, verbose_name='sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Faqat matematika — universitet imtihoniga onlayn tayyorgarlik', max_length=200, verbose_name='qisqa tavsif'),
        ),
    ]
