# Generated by Django 5.1.4 on 2026-07-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('text', models.CharField(max_length=500, verbose_name='javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="to'g'ri javobmi")),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('total_questions', models.PositiveIntegerField(verbose_name='savollar soni')),
                ('correct_answers', models.PositiveIntegerField(verbose_name="to'g'ri javoblar")),
                ('wrong_answers', models.PositiveIntegerField(verbose_name="noto'g'ri javoblar")),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='foiz (%)')),
                ('is_passed', models.BooleanField(default=False, verbose_name="o'tdimi")),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='sarflangan vaqt (soniya)')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='education.topic', verbose_name='mavzu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('question_count', models.PositiveIntegerField(default=10, verbose_name='savollar soni')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Masalan: 70, 80, 85, 90', verbose_name="o'tish foizi (%)")),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='vaqt limiti (daqiqa, ixtiyoriy)')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_settings', to='education.topic', verbose_name='mavzu')),
            ],
            options={
                'verbose_name': 'Test sozlamasi',
                'verbose_name_plural': 'Test sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('text', models.TextField(verbose_name='savol matni')),
                ('explanation', models.TextField(blank=True, help_text="Natija sahifasida ko'rsatiladi.", verbose_name='tushuntirish')),
                ('difficulty', models.CharField(choices=[('EASY', 'Oson'), ('MEDIUM', "O'rta"), ('HARD', 'Qiyin'), ('EXPERT', 'Ekspert')], default='MEDIUM', max_length=10, verbose_name='qiyinlik')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.topic', verbose_name='mavzu')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exam.examattempt')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exam.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exam.question')),
            ],
            options={
                'verbose_name': 'Urinish savoli',
                'verbose_name_plural': 'Urinish savollari',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question', verbose_name='savol'),
        ),
    ]
