# Generated by Django 5.1.4 on 2026-07-29 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Rejalashtirilgan'), ('LIVE', 'Jonli'), ('ENDED', 'Tugagan')], default='SCHEDULED', max_length=20, verbose_name='holat')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='boshlangan')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='tugagan')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_live_sessions', to=settings.AUTH_USER_MODEL, verbose_name='o‘qituvchi')),
            ],
            options={
                'verbose_name': 'Jonli efir',
                'verbose_name_plural': 'Jonli efirlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('text', models.CharField(max_length=500, verbose_name='matn')),
                ('is_from_teacher', models.BooleanField(default=False, verbose_name='o‘qituvchi javobi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live.livesession', verbose_name='efir')),
            ],
            options={
                'verbose_name': 'Jonli chat xabari',
                'verbose_name_plural': 'Jonli chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
