# Generated by Django 5.1.4 on 2026-08-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_platform_major_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='YouTube jonli efir (yoki video) havolasi. Kiritilsa, kamera o‘rniga shu efir ko‘rsatiladi.', max_length=300, verbose_name='YouTube havolasi'),
        ),
    ]
