# Generated by Django 5.1.4 on 2026-08-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_livesession_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='youtube_url',
        ),
    ]
