# Generated by Django 5.1.4 on 2026-07-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='education.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='education.subject', verbose_name='fan'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Oson'), ('MEDIUM', "O'rta"), ('HARD', 'Qiyin'), ('EXPERT', 'Ekspert')], default='MEDIUM', help_text="Bu mavzuning umumiy darajasi. Savol tanlashda ishlatilmaydi — faqat o'quv dasturini tashkil qilish uchun.", max_length=10, verbose_name='qiyinlik darajasi (curriculum uchun)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='education.module', verbose_name='modul')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('video', models.FileField(upload_to='videos/', verbose_name='video fayl')),
                ('pdf_material', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name="qo'shimcha material (PDF)")),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='davomiyligi (daqiqa)')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.topic', verbose_name='mavzu')),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
