# Generated by Django 5.1.4 on 2026-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lesson_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Belgilangan dars platformada bepul ochiladi. Tartib o‘zgarsa ham o‘zgarmaydi.', verbose_name='bepul sinov darsi'),
        ),
    ]
