# Generated by Django 5.1.4 on 2026-07-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_lesson_is_free_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
    ]
