# Generated by Django 5.1.4 on 2026-07-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('start_date', models.DateField(verbose_name='boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='tugash sanasi')),
                ('duration_days', models.PositiveIntegerField(verbose_name='davomiyligi (kun)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('EXPIRED', 'Muddati tugagan')], default='ACTIVE', max_length=10, verbose_name='holati')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='kim tomonidan faollashtirilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
