# Generated by Django 5.1.4 on 2026-07-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('label', models.CharField(max_length=80, verbose_name='sarlavha')),
                ('channel_type', models.CharField(choices=[('PHONE', 'Telefon'), ('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Boshqa')], default='OTHER', max_length=20, verbose_name='turi')),
                ('value', models.CharField(help_text='Masalan: +99890..., hello@xyz.uz, @username', max_length=255, verbose_name='qiymat')),
                ('url', models.URLField(blank=True, help_text='Ixtiyoriy: bosilganda ochiladigan to‘liq URL', verbose_name='havola')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons nomi, masalan: bi-telegram, bi-envelope', max_length=40, verbose_name='ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='izoh')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
