# Generated by Django 5.1.4 on 2026-07-27 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_contactchannel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('full_name', models.CharField(max_length=120, verbose_name='to‘liq ism')),
                ('phone', models.CharField(max_length=30, verbose_name='telefon')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('plan_days', models.PositiveIntegerField(verbose_name='tarif (kun)')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', 'Bog‘lanildi'), ('DONE', 'Bajarildi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='holat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_requests', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Obuna so‘rovi',
                'verbose_name_plural': 'Obuna so‘rovlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
