# Generated by Django 5.1.4 on 2026-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan sana')),
                ('title', models.CharField(max_length=80, verbose_name='sarlavha')),
                ('price_uzs', models.PositiveIntegerField(verbose_name='narx (so‘m)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='davomiyligi (kun)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='tavsif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='tavsiya etiladi')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'Obuna narxi',
                'verbose_name_plural': 'Obuna narxlari',
                'ordering': ['order', 'duration_days', 'id'],
            },
        ),
    ]
